# Generated by Django 5.0.13 on 2025-07-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_contactinformation_newscategory_newstag_newsarticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcategory',
            name='icon_class',
            field=models.CharField(blank=True, help_text="CSS class for the icon (e.g., 'fas fa-briefcase')", max_length=100),
        ),
    ]
