# Generated by Django 5.0.13 on 2025-07-02 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_jobcategory_icon_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='organizations/logos/')),
                ('website', models.URLField(blank=True, null=True)),
                ('application_instructions', models.TextField(blank=True, help_text='Instructions on how to apply for jobs at this organization.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Organizations',
            },
        ),
        migrations.AddField(
            model_name='job',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='portal.organization'),
        ),
    ]
