# Generated by Django 5.0.13 on 2025-07-05 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_cvprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cvprofile',
            name='attachments',
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='cv/attachments/')),
                ('cv_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='portal.cvprofile')),
            ],
            options={
                'verbose_name_plural': 'Attachments',
            },
        ),
    ]
